name: pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --local user.name "GitHub Action"
      - run: npm install
      - run: npm run deploy
